apiVersion: "spec.keptn.sh/0.2.3"
kind: "Shipyard"
metadata:
  name: "ortelius"
spec:
  stages:
    - name: "dev"
      sequences:
      - name: "kickoff"
        tasks:
        - name: "catalog"
        - name: "test"
        - name: "evaluation"
        - name: "pr"
    - name: "production"
      sequences:
      - name: "qualitycheck"
        triggeredOn:
          - event: "dev.kickoff.finished"
            selector:
              match:
              result: "pass"
        tasks:
        - name: "evaluation"
